#@data/values

#@overlay/match-child-defaults missing_ok=True
---
tap:
  credentials:
    tanzuNet:
      host: registry.tanzu.vmware.com
      username: TANZUNET_USERNAME
      password: TANZUNET_PASSWORD
    registry:
      username: REGISTRY_USERNAME
      password: REGISTRY_PASSWORD
    k8s_ca: b64encoded_ca
    k8s_url: https://apiserver:6443
    metadata_ca_cert_data:
